# Generated by Django 4.2.7 on 2025-03-30 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueSearch',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('radius', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_response', models.TextField()),
                ('search_type', models.CharField(choices=[('venue', 'Venue'), ('opportunity', 'Networking Opportunity')], default='venue', max_length=20)),
                ('search_terms', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Venue searches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VenueResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('data', models.JSONField()),
                ('imported', models.BooleanField(default=False)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('result_type', models.CharField(choices=[('venue', 'Venue'), ('opportunity', 'Networking Opportunity')], default='venue', max_length=20)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='ai.venuesearch')),
            ],
            options={
                'verbose_name_plural': 'Venue results',
                'ordering': ['index'],
                'unique_together': {('search', 'index')},
            },
        ),
    ]
