# Generated by Django 4.2.7 on 2025-04-02 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_code_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
