# Generated by Django 4.2.7 on 2025-03-30 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0003_remindercategory_reminder_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='reminder',
            name='recurrence_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='due_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='recurrence',
            field=models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('custom', 'Custom')], default='none', max_length=20),
        ),
    ]
