# Generated by Django 4.2.7 on 2023-04-12 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0004_reminder_priority_reminder_recurrence_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='recurrence',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='recurrence_end_date',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='custom_days',
        ),
    ] 