# Generated by Django 4.2.7 on 2025-03-30 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0005_remove_recurrence_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RenameField(
            model_name='remindernotification',
            old_name='created_at',
            new_name='sent_at',
        ),
        migrations.AddField(
            model_name='remindernotification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='remindernotification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='remindernotification',
            name='message',
        ),
    ]
