# Generated by Django 4.2.7 on 2025-04-02 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0007_auto_20250329_2328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remindernotification',
            options={'ordering': ['-sent_at']},
        ),
    ]
