# Generated by Django 4.2.7 on 2025-03-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='url',
            field=models.URLField(help_text='Must be a valid URL with http:// or https://'),
        ),
    ]
